name: Release GitHub Actions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
      setup_node:
        description: "Whether node.js should be setup or not"
        required: false
        type: boolean
        default: true
      node_version:
        description: "Specify Node.js version (e.g., '18', '20', 'lts/*')"
        required: false
        type: string
        default: "24"
      script:
        description: "Specify a script to run after audit fix"
        required: false
        default: "./build build" 

permissions:
  contents: read

jobs:
  release:
    permissions:
      actions: read
      id-token: write
      contents: write

    uses: step-security/reusable-workflows/.github/workflows/actions_release.yaml@fix/gradle-actions
    with:
      tag: "${{ github.event.inputs.tag }}"
      setup_node: ${{ github.event.inputs.setup_node == 'true' }}
      node_version: ${{ github.event.inputs.node_version}}
      script: ${{ inputs.script || './build build' }}
