name: CI-check-and-unit-test

on:
  push:
    branches:
    - 'main'
    - 'release/**'
    paths-ignore:
    - 'dist/**'
  pull_request:

permissions:
  contents: read

jobs:
  check-format-and-unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - name: Checkout sources
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: sources/package-lock.json
    - name: Setup Gradle
      # Use a released version to avoid breakages
      uses: ./setup-gradle
      env:
        ALLOWED_GRADLE_WRAPPER_CHECKSUMS: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 # Invalid wrapper jar used for testing
      with:
        gradle-version: '8.14.2'

    - name: Install npm dependencies
      run: |
        npm clean-install
      working-directory: sources

    - name: Check formatting and compile
      run: |
        npm run check
        npm run compile
      working-directory: sources

    - name: Run unit tests
      run: |
        npm test
      working-directory: sources
